version: '3'

services:
  
  testsitelocal_nginx:
    build: ./nginx/
    #image: nginx:alpine
    volumes:
      - ./../src:/srv/www
      - ./configs/vserver.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    restart: always
      
    networks:
      - lemp

  testsitelocal_php:
    build: ./php/
    #image: php:fpm-alpine
    volumes:
      - ./../src:/srv/www
    networks:
        - lemp
    restart: always



networks:
    lemp:
        driver: bridge
